#!/usr/bin/env python
import os
import subprocess

PROJECT_DIRECTORY = os.path.realpath(os.path.curdir)

def remove_file(filepath):
    os.remove(os.path.join(PROJECT_DIRECTORY, filepath))

if __name__ == '__main__':
    print('Project {{cookiecutter.project_name}} generated!')

    msg = 'Initial commit generated by equinor-cookiecutter'
    username = '{{ cookiecutter.github_username }}'
    repo = '{{ cookiecutter.repo_name }}'
    upstream = 'git@github.com:{}/{}'.format(username, repo)

    subprocess.check_call(['git', 'init'])
    subprocess.check_call(['git', 'add', '--all'])
    subprocess.check_call(['git', 'commit', '-m', msg])
    subprocess.check_call(['git', 'remote', 'add', 'upstream', upstream])

    if 'Not open source' in '{{ cookiecutter.open_source_license }}':
       remove_file('LICENSE')

    if '{{ cookiecutter.command_line_interface }}' == 'None':
        pkg = '{{ cookiecutter.package_name }}'
        remove_file(os.path.join(pkg, 'cli.py'))
        remove_file(os.path.join(pkg, '__main__.py'))

    print('\nNext steps:')

    travis = 'https://travis-ci.com'
    print('\tSet up the travis job:')
    print('\t{}\n'.format(travis))

    appveyor = 'https://ci.appveyor.com/projects/new'
    print('\tSet up the appveyor job:')
    print('\t{}\n'.format(appveyor))

    sphinx = 'https://readthedocs.org/dashboard/import'
    print('\tSet up the sphinx job:')
    print('\t{}\n'.format(sphinx))

    if '{{ cookiecutter.pypi }}' == 'yes':
        print('\tSet the pypi username and encrypted password in .travis.yml:')
        print('\thttps://docs.travis-ci.com/user/encryption-keys')

    print()
